### ISSUE TITLE
Godot multiple clients throws error

### ISSUE THREAD

**Issue by AngelOnFira** [rivet-gg/plugin-godot#129]
<img src="https://uploads.linear.app/296b26dd-14fd-4d1f-aa10-714d93154ee5/09f9fd67-63fb-483f-82b4-4cd7a4329f8f/dd9c78e5-4d3d-4664-91d3-8463a0b1a484?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI5NmIyNmRkLTE0ZmQtNGQxZi1hYTEwLTcxNGQ5MzE1NGVlNS8wOWY5ZmQ2Ny02M2ZiLTQ4M2YtODJiNC00Y2Q3YTQzMjlmOGYvZGQ5Yzc4ZTUtNGQzZC00NjY0LTkxZDMtODQ2M2EwYjFhNDg0IiwiaWF0IjoxNzE5MjU2NzM5LCJleHAiOjMzMjg5ODE2NzM5fQ.Ed0ZQTlWIKGPIKep58tvLh6wPgVxFsRal6W8ZxSlaRY " alt="image.png" width="1117" height="258" />

This happens when two clients locally try connecting to the same remote server. Running a local server is fine.

**Comment by epsilonmb** [comment]
I encountered this issue occasionally after calling Rivet.matchmaker.lobbies.find. Has it been resolved yet?
