### ISSUE TITLE
Show progress when deploying/running CLI commands.

### ISSUE THREAD

**Issue by maji-git** [rivet-gg/plugin-godot#171]
So usually (for me). When I'm deploying my Rivet game, it'll build a Docker image, This process do take quite some time. Especially with first time build.

I find myself using Rivet CLI instead of Godot Plugin, just because when using the plugin. It doesn't show the progress and the logs. And I do find logs and status indication essential in deployment process, especially when building a Docker image. 

P.S. Also Godot 4.3 just introduced [OS.execute_with_pipe](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-execute-with-pipe) function. Which does execute program without blocking the main thread. It might be a great start for this feature. (Which also means it could be a Godot 4.3 only thing, unless there's some modification with the toolchain or CLI)

(not really an issue, but rather a suggestion. sorry for bad english)

**Comment by NathanFlurry** [comment]
@maji-git v2.0 should have a much cleaner experience for deploy process. open to further suggestions!
