### ISSUE TITLE
Errors when using on 64 bit machine

### ISSUE THREAD

**Issue by jonahmschreiner** [rivet-gg/plugin-godot#177]
Upon extracting .zip plugin into /addons folder in godot, it errors saying "Contact software vendor for 64 bit version".

Running on Windows 10 64-bit machine.

Same error pops up upon clicking "Sign in to Rivet" in the FileSystem window

**Comment by AngelOnFira** [comment]
Interesting, could you send a screenshot of that? The "contact software vendor" part seems quite out of the ordinary.

We are also pushing a new version that _should_ be a lot easier to install, the version should be out in just a few hours.

**Comment by jonahmschreiner** [comment]
Sounds good.

To reproduce:
1. Created new godot project: 4.2.2.stable, "Mobile" project mode, Windows 10 64-bit machine
2. Added "/addons" folder under "res://" in FileSystem (bottom left side)
3. Dragged "/rivet" folder from "addons/rivet" into godot project "/addons" folder as described in the plugin readme
4. Went to project settings -> plugins -> checked the enable box for "Rivet - Multiplayer Game Servers and Backend" and 4-5 windows of the following windows error popup appeared

![RivetError](https://github.com/user-attachments/assets/dc308d35-5700-407a-92aa-3d84cb8783d7)

Lmk when the new version is out and maybe it'll be fixed?

**Comment by AngelOnFira** [comment]
Great, thanks for the debug logs on this. I agree, this is quite odd. Looking into this today.

**Comment by jonahmschreiner** [comment]
How's it coming along? @AngelOnFira

**Comment by NathanFlurry** [comment]
@jonahmschreiner hey! fix is in the works, will submit it within 48h & ping you here.

the issue you saw on 2.0.1 a bit of a nasty bug specific to windows, we need to rework how logs get passed from the local game server to the engine.

**Comment by NathanFlurry** [comment]
@jonahmschreiner 2.1.0 uses a new FFI-based architecture instead of the CLI, so this should be fixed.
