### ISSUE TITLE
Class "RivetClient" hides an autoload singleton.

### ISSUE THREAD

**Issue by maji-git** [rivet-gg/plugin-godot#276]
At line 6,12. RivetClient class name seems to overlap with the autoload singleton's name.
Located at `res://addons/rivet_sdk/client/client.gd`

![image](https://github.com/user-attachments/assets/47c25efc-8830-45a9-a782-a34ba7622b55)

**Comment by NathanFlurry** [comment]
hey! it looks like you're upgrading from a previous version of the plugin, correct? you can safely remove the RivetClient autoload, it's been ranmed to just `Rivet`.

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/ee2771ec-bd8c-45cd-91eb-44211d84813b">

<img width="457" alt="image" src="https://github.com/user-attachments/assets/f52e7334-0fb2-4e87-b077-674fafd419e0">
